/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_zbw_interphone_serialport_SerialPort */

#ifndef _Included_com_zbw_interphone_serialport_SerialPort
#define _Included_com_zbw_interphone_serialport_SerialPort
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_zbw_interphone_serialport_SerialPort
 * Method:    open
 * Signature: (Ljava/lang/String;I)Ljava/io/FileDescriptor;
 */
JNIEXPORT jobject JNICALL Java_com_zbw_interphone_serialport_SerialPort_open
  (JNIEnv *, jclass, jstring, jint);

/*
 * Class:     com_zbw_interphone_serialport_SerialPort
 * Method:    close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_zbw_interphone_serialport_SerialPort_close
  (JNIEnv *, jobject);

/*
 * Class:     com_zbw_interphone_serialport_SerialPort
 * Method:    test
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_zbw_interphone_serialport_SerialPort_test
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
